<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">
	<p style="font-size:xx-small">Copyright &copy; 2011 by:
	Alex Lucyk, Jesus Navarro, and Allen Tucker.<br />
	<i>Homeroom</i> was designed at <a href="http://www.bowdoin.edu/computer-science/" style="font-weight:normal;">Bowdoin College</a> for the <a href="http://www.rmhportlandme.org/" target="_BLANK" style="font-weight:normal;">Ronald McDonald House of Portland, Maine</a>. 
	      It is free software and comes with absolutely no warranty.  You can redistribute and/or modify it under the terms of the
	     <a href="http://www.gnu.org/copyleft/gpl.html" style="font-weight:normal;"> GNU General Public License</a> as published by the <a href="http://www.fsf.org/"  style="font-weight:normal;"> Free Software Foundation</a>.
	</p>
</div>
</div>
<!-- End Footer -->