<?PHP
	session_start();
	session_cache_expire(30);
	include_once('database/dbPersons.php');
    include_once('domain/Person.php');
	$id = $_GET["id"];
	$person = retrieve_dbPersons($id);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Viewing <?PHP echo($person->get_first_name()." ".$person->get_last_name()); ?>
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<?PHP
				 if(!$person){
						//there is no person
						echo('<p id="error">Error: there\'s no person with this id in the database</p>');
						include('footer.inc');
						echo('</div></div></body></html>');
						die();
				}
				else {
					$nice_phone_1 = substr($person->get_phone1(),0,3)."-".substr($person->get_phone1(),3,3)."-".substr($person->get_phone1(),6,4);
					if($person->get_phone2() !== "")
						$nice_phone_2 = substr($person->get_phone2(),0,3)."-".substr($person->get_phone2(),3,3)."-".substr($person->get_phone2(),6,4);;
					echo("<p>Contact information for " . $person->get_first_name() . " " . $person->get_last_name()."<br />");
					if($_SESSION['_id']==$person->get_id() || $_SESSION['access_level']>=2)
						echo("<span style=\"font-size:x-small;\">To view entire profile, select <a href=\"personEdit.php?id=".$person->get_id()."\">edit</a>.</span>");
					echo("</p><p>");
					echo("<table class=\"searchResults\"><tr><td colspan=\"2\" class=\"searchResults\">".$person->get_first_name()." ".$person->get_last_name()."</td></tr>");
					echo("<tr><td class=\"searchResults\">Phone 1:</td><td class=\"searchResults\">".$nice_phone_1."</td></tr>");
					echo("<tr><td class=\"searchResults\">Phone 2:</td><td class=\"searchResults\">".$nice_phone_2."</td></tr>");
					echo("<tr><td class=\"searchResults\">Email:</td><td class=\"searchResults\"><a href=\"mailto:".$person->get_email()."\">".$person->get_email()."</a></td></tr>");
					if (in_array("guest",$person->get_type()))
					    echo("<tr><td class=\"searchResults\">Patient Name:</td><td class=\"searchResults\">".$person->get_patient_name()."</td></tr>");
					echo("</table></p>");
				}
				?>
				<!-- below is the footer that we're using currently-->
				<?PHP include('footer.inc');?>
			</div>
		</div>
	</body>
</html>
